### ISSUE TITLE
Issue with Speedle Integration makefile

### ISSUE THREAD

**Issue by ashishksingh** [oracle/speedle#21]
https://github.com/oracle/speedle/blob/master/samples/integration/istio-integration/Makefile , line#11 pulls the older version of Istio for installing Speedle. . 

We should remove the flags '--single-branch --branch release-1.0' to get the latest Istio version.

**Comment by caiwl** [comment]
@ashishksingh we hard-code the version because we only tested it against Istio 1.0. If you get a chance to verify it with later version(s), please let us know the result. We can expand the support list based on your findings. Your help will be greatly appreciated.

**Comment by alan-cao** [comment]
release-1.0 isn't compatible with latest release-1.2. I have a fix to upgrade it to release-1.2
