### ISSUE TITLE
Broken Link for token assertor and quick-start on  speedle.io/support page

### ISSUE THREAD

**Issue by jayrajput** [oracle/speedle#22]
The 'token assertor' link points to https://speedle.io/support/docs/assertor. It should be pointing to https://speedle.io/docs/assertor/. The broken link is seen in the last QA page on the https://speedle.io/support/ page.

**Comment by jayrajput** [comment]
https://speedle.io/support/quick-start also needs to fixed to https://speedle.io/quick-start

**Comment by caiwl** [comment]
GitHubAPP [8:22 PM]
caiwl
*1 new commit pushed to `master`*
`3061aba3` - fix broken links
oracle/speedle

caiwl
Successfully deployed `3061aba` to github-pages
oracle/speedle
caiwl
*1 new commit pushed to `master`*
`ac0e693b` - fix broken link
oracle/speedle
caiwl
Successfully deployed `ac0e693` to github-pages
oracle/speedle

**Comment by caiwl** [comment]
fixed the broken links.
