### ISSUE TITLE
speedle-pms attribute help for auditlog-reportcaller uses wrong prefix 'Log Config:' in place of 'Audit Log Config'

### ISSUE THREAD

**Issue by jayrajput** [oracle/speedle#23]
speedle-pms --help provided attribute prefix. for auditlog-reportcaller wrongly uses prefix Log config. It should be Audit Log config to be consistent with other attributes.

      --auditlog-reportcaller string       Log config: if the caller(file, line and function) is included in the log entry. (default "false")

**Comment by caiwl** [comment]
@ahrtr any idea?

**Comment by ahrtr** [comment]
@jayrajput Thanks for the finding, just fixed it @caiwl .

**Comment by ahrtr** [comment]
https://github.com/oracle/speedle/commit/8f80df42e4fc0d552ea5d0b07fdcd1f326a2d167

**Comment by caiwl** [comment]
thanks for the quick fix. @ahrtr
